language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
before_install:
    # Installing Arpeggio as a dependency
    - cd ..
    - pip install Jinja2
    - git clone --depth=1 --branch=master git://github.com/igordejanovic/Arpeggio.git
    - cd Arpeggio && python setup.py install
    - cd ../textX
install:
    - python setup.py install
script:
    - py.test tests/functional
